services:
  postgres:
    image: postgres:16
    container_name: kage-postgres
    environment:
      POSTGRES_DB: logging
      POSTGRES_USER: logging_user
      POSTGRES_PASSWORD: logging_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logging_user -d logging"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: kage-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: kage-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10

  ingestion-api:
    build:
      context: ./apps/ingestion-api
    container_name: kage-ingestion-api
    environment:
      POSTGRES_URL: postgres://logging_user:logging_pass@postgres:5432/logging
      REDIS_ADDR: redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      QUEUE_NAME: logs_ingestion
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  processor-worker:
    build:
      context: ./apps/processor-worker
    container_name: kage-processor-worker
    environment:
      POSTGRES_URL: postgres://logging_user:logging_pass@postgres:5432/logging
      REDIS_ADDR: redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      QUEUE_NAME: logs_ingestion
      ERROR_SPIKE_THRESHOLD: "5"
      ERROR_SPIKE_WINDOW_SEC: "300"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  query-api:
    build:
      context: ./apps/query-api
    container_name: kage-query-api
    environment:
      POSTGRES_URL: postgres://logging_user:logging_pass@postgres:5432/logging
      PORT: "8081"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: